app-id: com.github.expresslrs.ExpressLRSConfigurator
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: "22.08"
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node16
command: run.sh
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
build-options:
  # Add the node bin directory & yarn directory.
  append-path: /usr/lib/sdk/node16/bin:/app/yarn/bin:/run/build/github-desktop/flatpak-node/chromedriver
  env:
    NPM_CONFIG_LOGLEVEL: info
modules:
  - name: expresslrs-configurator
    buildsystem: simple
    build-options:
      env:
        # Sets the directory where Node is located so way npm won't download the headers.
        npm_config_nodedir: /usr/lib/sdk/node16
        # Set the Electron cache directory.
        ELECTRON_CACHE: /run/build/github-desktop/flatpak-node/electron-cache
        # Skip Electron related downloads
        ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
        OFFLINE: "1"
        CHROMEDRIVER_SKIP_DOWNLOAD: "true"
        # Use predownloaded dugite-native
        TMPDIR: /run/build/github-desktop/flatpak-node/tmp
        XDG_CACHE_HOME: /run/build/github-desktop/flatpak-node/cache
    build-commands:
      - HOME=$PWD yarn config --offline set yarn-offline-mirror
        $FLATPAK_BUILDER_BUILDDIR/flatpak-node/yarn-mirror
      - yarn --offline --verbose
      # Run electron-builder, passing the architecture arguments to it.
      - . flatpak-node/electron-builder-arch-args.sh; yarn
        run --offline package $ELECTRON_BUILDER_ARCH_ARGS
      # Bundle app and dependencies
      - cp -a dist/linux*unpacked /app/main
      # Install app wrapper
      - install -Dm755 -t /app/bin/ ../run.sh
    subdir: main
    sources:
      - type: archive
        url: https://github.com/ExpressLRS/ExpressLRS-Configurator/archive/refs/tags/v1.5.0.tar.gz
        sha256: 244c46b4a57d7869b0896679d4ba312457814a5d6505790585bcfbfa9c9c557d
      - type: dir
        path: ..
        dest: main
      - generated-sources.json
      # Wrapper to launch the app
      - type: script
        dest-filename: run.sh
        commands:
          - zypak-wrapper.sh /app/main/expresslrs-configurator "$@"
