app-id: com.github.expresslrs.ExpressLRSConfigurator
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: "22.08"
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node16
command: expresslrs-configurator
separate-locales: false
# rename-desktop-file: expresslrs-configurator.desktop
# rename-icon: expresslrs-configurator
# copy-icon: true
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
  - --device=all
# cleanup:
#   - /include
#   - /lib/pkgconfig
#   - /lib/*.la
#   - /lib/*.a
#   - /share/pkgconfig
#   - /share/aclocal
#   - /share/gtk-doc
#   - /share/doc
#   - /share/info
#   - /share/man
#   - /man
modules:
  - name: git
    make-args:
      - INSTALL_SYMLINKS=1
      - NO_PERL=YesPlease
      - NO_TCLTK=YesPlease
    make-install-args:
      - INSTALL_SYMLINKS=1
      - NO_PERL=YesPlease
      - NO_TCLTK=YesPlease
    post-install:
      - find . -type f -name perllocal.pod -delete
    sources:
      - type: archive
        sha256: 814641d7f61659cfbc17825d0462499ca1403e39ff53d76a8512050e6483e87a
        url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.37.3.tar.xz
        x-checker-data:
          type: html
          url: https://mirrors.edge.kernel.org/pub/software/scm/git/
          version-pattern: git-([\d\.-]+).tar.xz
          url-template: https://mirrors.edge.kernel.org/pub/software/scm/git/git-$version.tar.xz
  - name: expresslrs-configurator
    buildsystem: simple
    build-commands:
      - ar x expresslrs-configurator_*.deb
      - rm expresslrs-configurator_*.deb
      - tar xf data.tar.xz
      - cp -r 'opt/ExpressLRS Configurator' '/app/ExpressLRS-Configurator'
      - mkdir -p /app/share/icons/hicolor
      - cp -r usr/share/icons/hicolor/* /app/share/icons/hicolor
      - chmod -R a-s,go+rX,go-w "/app/ExpressLRS-Configurator"
      - install expresslrs-configurator.sh /app/bin/expresslrs-configurator
      - install -Dm644 com.github.expresslrs.ExpressLRSConfigurator.desktop /app/share/applications/com.github.expresslrs.ExpressLRSConfigurator.desktop
      - install -Dm644 com.github.expresslrs.ExpressLRSConfigurator.appdata.xml /app/share/metainfo/com.github.expresslrs.ExpressLRSConfigurator.metainfo.xml
    sources:
      - type: file
        only-arches:
          - x86_64
        url: https://github.com/ExpressLRS/ExpressLRS-Configurator/releases/download/v1.5.0/expresslrs-configurator_1.5.0_amd64.deb
        sha256: aaed239c5334a4c7ad7c3471cce00af6a5aeada3507a4beaa9354d5240c35721
      - type: file
        path: expresslrs-configurator.sh
      - type: file
        path: com.github.expresslrs.ExpressLRSConfigurator.desktop
      - type: file
        path: com.github.expresslrs.ExpressLRSConfigurator.appdata.xml
